version: '3.7'
services:
  rabbit:
    image: rabbitmq:3.7.7
    restart: always
  db:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTRGES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  registry:
    build: registry-service
  zuulgateway:
    build: zuul-gateway
    depends_on:
      - registry
  userservice:
    build: user-service
    depends_on:
      - rabbit
      - db
      - zuulgateway
  catservice:
    build: cat-service
    depends_on:
      - rabbit
      - zuulgateway
  uiserver:
    build: ui-server
    depends_on:
      - rabbit
