zuul:
  prefix: /api
  routes:
    user:
      path: /users/**
      serviceId: USERSERVICE

server:
  port: 8081

spring:
  application:
    name: ZuulGateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
  instance:
    prefer-ip-address: true